### ISSUE TITLE
Unsafe Map Operations Causing Panic

### ISSUE THREAD

**Issue by bradleypeabody** [orderbynull/lottip#5]
In proxy.go you're doing all kinds of unsafe map operations.  The program panics almost immediately when I try to run under any load.  Please have a look at https://golang.org/doc/faq#atomic_maps .  If I have a chance to put in PR with a fix I will, but haven't had time just yet.  One common approach would be to add a sync.Mutex (or sync.RWMutex) and use that around map access calls.

**Comment by orderbynull** [comment]
Hello, thanks for your report. You're totally right. I've tested lottip with a lot of queries per sec but all within few connections so i missed concurrent map writes. I'll test and accept your PR. Thanks again.
