### ISSUE TITLE
[Question] Production readiness

### ISSUE THREAD

**Issue by ktugan** [orderbynull/lottip#7]
Hi,

I wanted to ask your opinion on the production readiness of the proxy. I would like to run it between hundreds of clients and multiple databases including replicas.

Do you think it can handle handle this with grace?

**Comment by orderbynull** [comment]
Hi,

It was not designed for production use in any way. It's not optimized in terms of stability and performance.

**Comment by ktugan** [comment]
Thank you, I thought so already but hoped :) 

Its an awesome nifty tool!
