### ISSUE TITLE
User Filtering Question

### ISSUE THREAD

**Issue by ecetiner87** [orderbynull/lottip#8]
Hi,
Thank you for this great application. It is very useful to have overall view on query profiling of mysql DB.

Since there is no Wiki page, I used **Issues** panel to ask this question. Is it possible to filter queries by USER on this app? For example; I want to know queries executed by a specific user X. Can this application handle this?

I have tens of mysql DB running for a realtime application and there are 5 admin accounts who have root privileges on those and I want to track each user action. I know this can be done via general.log or slow.log, however it impacts performance dramatically. 

Currently I used Mysql-Proxy as workaround. Having such a feature as GUI will be very helpful indeed.

Regards.

**Comment by orderbynull** [comment]
Hi Erkan,
Unfortunately No at this moment. I'll think how to implement that in next versions.
Thanks for your feedback.
